name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit"]
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v4
      - name: build
        run: luarocks make
      - name: test
        run: luarocks test
